# Generated by Django 6.0.3 on 2026-03-13 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('quarter', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Квартал')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Квартал',
                'verbose_name_plural': 'Кварталы',
                'constraints': [models.UniqueConstraint(fields=('year', 'quarter'), name='unique_okr_quarter_per_year')],
            },
        ),
    ]
