# Generated by Django 6.0.3 on 2026-03-13 21:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('okr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Okr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активный'), ('on_track', 'В графике'), ('at_risk', 'Под риском'), ('off_track', 'Вне графика'), ('completed', 'Завершён'), ('archived', 'Архивирован')], default='draft', max_length=32, verbose_name='Статус')),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прогресс')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_okrs', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_okrs', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='okrs', to='okr.quarter', verbose_name='Период')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='okrs', to='core.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'OKR',
                'verbose_name_plural': 'OKR',
            },
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('metric_type', models.CharField(choices=[('number', 'Число'), ('percent', 'Процент'), ('currency', 'Деньги'), ('boolean', 'Да/Нет')], default='number', max_length=32, verbose_name='Тип метрики')),
                ('start_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стартовое значение')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Текущее значение')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Целевое значение')),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прогресс')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активный'), ('on_track', 'В графике'), ('at_risk', 'Под риском'), ('off_track', 'Вне графика'), ('completed', 'Завершён'), ('archived', 'Архивирован')], default='draft', max_length=32, verbose_name='Статус')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('okr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='okr.okr', verbose_name='OKR')),
            ],
            options={
                'verbose_name': 'Ключевой результат',
                'verbose_name_plural': 'Ключевые результаты',
                'constraints': [models.UniqueConstraint(fields=('okr', 'order'), name='unique_key_result_order_per_okr')],
            },
        ),
    ]
