# Generated by Django 6.0.3 on 2026-03-13 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0002_okr_keyresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('entity_type', models.CharField(choices=[('okr', 'OKR'), ('key_result', 'Ключевой результат'), ('check_in', 'Check-in'), ('comment', 'Комментарий')], max_length=32, verbose_name='Тип сущности')),
                ('entity_id', models.PositiveBigIntegerField(verbose_name='Идентификатор сущности')),
                ('action', models.CharField(choices=[('created', 'Создание'), ('updated', 'Изменение')], max_length=32, verbose_name='Действие')),
                ('payload', models.JSONField(default=dict, verbose_name='Данные')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_logs', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'История изменений',
                'verbose_name_plural': 'История изменений',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('previous_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Предыдущее значение')),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Новое значение')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='key_result_check_ins', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('key_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='okr.keyresult', verbose_name='Ключевой результат')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-in',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('text', models.TextField(verbose_name='Текст')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='okr_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('okr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='okr.okr', verbose_name='OKR')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
